services:
  - type: web
    name: ea-converter-web
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: EXPO_NO_TELEMETRY
        value: "1"
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "3000"

